[workspace]
members = [
    # Исполняемая программа
    "crates/checkers-app",
    # Библиотека логики поведения шашек
    "crates/checkers-lib"
]
resolver = "2"

[workspace.package]
authors = ["Сырцев Вадим Игоревич <syrtcevvi@gmail.com>"]
description = "Игра Шашки"
edition = "2021"
